### PR TITLE
Feature request time delayed

### PR DESCRIPTION
**Pull request by nfg**
Hello! I came across this package today, and noticed that request_duration is being calculated early. This should make it reflect the entire duration of the response.

Let me know if there's anything that should be changed.

Cheers!

### CODE REVIEW

**Comment by mstock** [comment]
Looks good, and thanks for the pull request! Three small things though:
* To get better diagnostics in case of a failure, I'd use `cmp_ok` instead of `ok` in the last assertion of the new test.
* The rest of the code uses the `my ($var) = @_;`-approach to argument unpacking (instead of `shift`ing parameters), so to increase consistency, it would be nice if you could change the test accordingly.
* It would be good if you could squash the second commit into the first one (also applies to the new commits if you make the above changes), I usually prefer to not have commits in a feature branch that correct an earlier 'mistake' on the same feature branch.

**Comment by nfg** [comment]
Sounds reasonable. Also, I just noticed that request_duration is in milliseconds, not seconds, so I should check for request_duration > 1000 instead of 1. Cheers!

**Comment by mstock** [comment]
Thanks :), you seem to have missed a `my $responder = shift;` in the delayed response coderef though. With this changed, I think it will be ready to merge and release.

**Comment by nfg** [comment]
Here you go!

**Comment by mstock** [comment]
Thank you :). I have also done a [release to CPAN](https://metacpan.org/release/MSTOCK/Plack-Middleware-AccessLog-Structured-0.001002) by now which includes your change.

**Pull request merged**
